version: "3.8"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # ✅ Updated path
    environment:
      - DATABASE_URL=postgresql+asyncpg://quantum_user:dido@db:5432/dido_quantum_db
    depends_on:
      - db
    restart: always


  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: quantum_user
      POSTGRES_PASSWORD: dido
      POSTGRES_DB: dido_quantum_db
    ports:
      - "5433:5432"  # Avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dido.com
      PGADMIN_DEFAULT_PASSWORD: root  
volumes:
  postgres_data:
  pgadmin_data:

